### ISSUE TITLE
Linux CI builds missing executable flags on main binary and hactool

### ISSUE THREAD

**Issue by tech-ticks** [tech-ticks/SkyEditor.RomEditor.Rtdx#57]
Probably caused by action `actions/upload-artifact@v2`, are there some properties we can set to fix it? Workaround: .zip the artifacts manually and upload the .zip

**Comment by evandixon** [comment]
Caused by https://github.com/actions/upload-artifact/issues/38

See https://github.com/actions/upload-artifact/issues/38#issuecomment-692890931 for potential workaround
